<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="linkedlist" nsURI="http://bento/sirius/tests/linked_list" nsPrefix="linked_list">
  <eClassifiers xsi:type="ecore:EClass" name="LinkedList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//AbstractListNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractListNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//AbstractListNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode" eSuperTypes="#//AbstractListNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListNode" eSuperTypes="#//AbstractListNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalNode" eSuperTypes="#//AbstractListNode"/>
</ecore:EPackage>
