/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package bento.language.bentocomp.resource.bento.grammar;

public class BentoGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public final static BentoGrammarInformationProvider INSTANCE = new BentoGrammarInformationProvider();
	
	private java.util.Set<String> keywords;
	
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_0_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.dsl.DslPackage.eINSTANCE.getDefinitionRoot().getEStructuralFeature(bento.language.bentocomp.dsl.DslPackage.DEFINITION_ROOT__COMPONENT), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getComponent(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_0_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_0 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.dsl.DslPackage.eINSTANCE.getDefinitionRoot(), BENTO_0_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("transformation", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("component", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_1_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__NAME), "QNAME", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_3 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("{", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_4_0_0_0_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("source", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_1_0_0_4_0_0_0_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__SOURCE), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getConcept(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_4_0_0_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_4_0_0_0_0_0_0, BENTO_1_0_0_4_0_0_0_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_4_0_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_4_0_0_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_4_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_4_0_0_0_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_4_0_0_1_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("target", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_1_0_0_4_0_0_1_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__TARGET), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getConcept(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_4_0_0_1_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_4_0_0_1_0_0_0, BENTO_1_0_0_4_0_0_1_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_4_0_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_4_0_0_1_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_4_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_4_0_0_1_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_4_0_0_2_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("source", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_1_0_0_4_0_0_2_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__SOURCE_MODELS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getParameterModel(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_4_0_0_2_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_4_0_0_2_0_0_0, BENTO_1_0_0_4_0_0_2_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_4_0_0_2_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_4_0_0_2_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_4_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_4_0_0_2_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_4_0_0_3_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("target", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_1_0_0_4_0_0_3_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__TARGET_MODELS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getParameterModel(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_4_0_0_3_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_4_0_0_3_0_0_0, BENTO_1_0_0_4_0_0_3_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_4_0_0_3_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_4_0_0_3_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_4_0_0_3 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_4_0_0_3_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_4_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_4_0_0_0, BENTO_1_0_0_4_0_0_1, BENTO_1_0_0_4_0_0_2, BENTO_1_0_0_4_0_0_3);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_4_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_4_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_4 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_4_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.PLUS);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_5_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("variants", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_1_0_0_5_0_0_1_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__FORMAL_PARAMETERS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.variants.VariantsPackage.eINSTANCE.getParameter(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_5_0_0_1_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_5_0_0_1_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_5_0_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_5_0_0_1_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_5_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_5_0_0_1_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.PLUS);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_5_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_5_0_0_0, BENTO_1_0_0_5_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_5_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_5_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_5 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_5_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.QUESTIONMARK);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_6 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("definition", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_1_0_0_7 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__TEMPLATE), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getTemplate(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_8_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("version", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_1_0_0_8_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__VERSION), "QUOTED_34_34", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_8_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_8_0_0_0, BENTO_1_0_0_8_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_8_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_8_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_8 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_8_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.QUESTIONMARK);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_9_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("contributos", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_1_0_0_9_0_0_1_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__CONTRIBUTORS), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_9_0_0_1_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_9_0_0_1_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_1_0_0_9_0_0_1_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__CONTRIBUTORS), "QUOTED_34_34", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_9_0_0_1_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_9_0_0_1_0_1_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_9_0_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_9_0_0_1_0_0, BENTO_1_0_0_9_0_0_1_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_9_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_9_0_0_1_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_9_0_0_2_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(",", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_1_0_0_9_0_0_2_0_0_1_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__CONTRIBUTORS), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_9_0_0_2_0_0_1_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_9_0_0_2_0_0_1_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_1_0_0_9_0_0_2_0_0_1_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__CONTRIBUTORS), "QUOTED_34_34", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_9_0_0_2_0_0_1_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_9_0_0_2_0_0_1_0_1_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_9_0_0_2_0_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_9_0_0_2_0_0_1_0_0, BENTO_1_0_0_9_0_0_2_0_0_1_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_9_0_0_2_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_9_0_0_2_0_0_1_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_9_0_0_2_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_9_0_0_2_0_0_0, BENTO_1_0_0_9_0_0_2_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_9_0_0_2_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_9_0_0_2_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_9_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_9_0_0_2_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.STAR);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_9_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_9_0_0_0, BENTO_1_0_0_9_0_0_1, BENTO_1_0_0_9_0_0_2);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_9_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_9_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_9 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_9_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.QUESTIONMARK);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_10_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("tags", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_1_0_0_10_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__TAGS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getTag(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_10_0_0_2_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(",", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_1_0_0_10_0_0_2_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TRANSFORMATION_COMPONENT__TAGS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getTag(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_10_0_0_2_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_10_0_0_2_0_0_0, BENTO_1_0_0_10_0_0_2_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_10_0_0_2_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_10_0_0_2_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_10_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_10_0_0_2_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.STAR);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0_10_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_10_0_0_0, BENTO_1_0_0_10_0_0_1, BENTO_1_0_0_10_0_0_2);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0_0_10_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_10_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_1_0_0_10 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_1_0_0_10_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.QUESTIONMARK);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_1_0_0_11 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("}", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_1_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0_0, BENTO_1_0_0_1, BENTO_1_0_0_2, BENTO_1_0_0_3, BENTO_1_0_0_4, BENTO_1_0_0_5, BENTO_1_0_0_6, BENTO_1_0_0_7, BENTO_1_0_0_8, BENTO_1_0_0_9, BENTO_1_0_0_10, BENTO_1_0_0_11);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_1_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_1 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTransformationComponent(), BENTO_1_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_2_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("concept", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_2_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getConcept().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.CONCEPT__NAME), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_2_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(":", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_2_0_0_3 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getConcept().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.CONCEPT__URI), "QUOTED_34_34", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_2_0_0_4_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("tags", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_2_0_0_4_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getConcept().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.CONCEPT__TAGS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getTag(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_2_0_0_4_0_0_2_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(",", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_2_0_0_4_0_0_2_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getConcept().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.CONCEPT__TAGS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getTag(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_2_0_0_4_0_0_2_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_2_0_0_4_0_0_2_0_0_0, BENTO_2_0_0_4_0_0_2_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_2_0_0_4_0_0_2_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_2_0_0_4_0_0_2_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_2_0_0_4_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_2_0_0_4_0_0_2_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.STAR);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_2_0_0_4_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_2_0_0_4_0_0_0, BENTO_2_0_0_4_0_0_1, BENTO_2_0_0_4_0_0_2);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_2_0_0_4_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_2_0_0_4_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_2_0_0_4 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_2_0_0_4_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.QUESTIONMARK);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_2_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_2_0_0_0, BENTO_2_0_0_1, BENTO_2_0_0_2, BENTO_2_0_0_3, BENTO_2_0_0_4);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_2_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_2_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_2 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.core.CorePackage.eINSTANCE.getConcept(), BENTO_2_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_3_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("model", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_3_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getParameterModel().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.PARAMETER_MODEL__NAME), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_3_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(":", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_3_0_0_3 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getParameterModel().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.PARAMETER_MODEL__TYPE), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_3_0_0_4_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("=", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_3_0_0_4_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getParameterModel().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.PARAMETER_MODEL__RESOURCE_NAME), "QUOTED_34_34", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_3_0_0_4_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_3_0_0_4_0_0_0, BENTO_3_0_0_4_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_3_0_0_4_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_3_0_0_4_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_3_0_0_4 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_3_0_0_4_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.QUESTIONMARK);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_3_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_3_0_0_0, BENTO_3_0_0_1, BENTO_3_0_0_2, BENTO_3_0_0_3, BENTO_3_0_0_4);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_3_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_3_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_3 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.core.CorePackage.eINSTANCE.getParameterModel(), BENTO_3_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_4_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTag().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TAG__VALUE), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_4_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_4_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_4_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTag().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.TAG__VALUE), "QUOTED_34_34", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_4_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_4_0_1_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_4_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_4_0_0, BENTO_4_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_4 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.core.CorePackage.eINSTANCE.getTag(), BENTO_4_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_5_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("-", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_5_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.variants.VariantsPackage.eINSTANCE.getSingleFeature().getEStructuralFeature(bento.language.bentocomp.variants.VariantsPackage.SINGLE_FEATURE__NAME), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_5_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_5_0_0_0, BENTO_5_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_5_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_5_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_5 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.variants.VariantsPackage.eINSTANCE.getSingleFeature(), BENTO_5_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_6_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("+", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_6_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.variants.VariantsPackage.eINSTANCE.getXorFeature().getEStructuralFeature(bento.language.bentocomp.variants.VariantsPackage.XOR_FEATURE__NAME), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_6_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("xor", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_6_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_6_0_0_0, BENTO_6_0_0_1, BENTO_6_0_0_2);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_6_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_6_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_6 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.variants.VariantsPackage.eINSTANCE.getXorFeature(), BENTO_6_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("composite", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("component", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_7_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__NAME), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_3 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("{", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_4_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("uses", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_7_0_0_4_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__USES), "QUOTED_34_34", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_4_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_4_0_0_0, BENTO_7_0_0_4_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_4_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_4_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_4 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_4_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.PLUS);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_7_0_0_5_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__BINDINGS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getBindingDeclaration(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_5_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_5_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_5_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_5_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_5 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_5_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.STAR);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_6_0_0_0_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("source", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_7_0_0_6_0_0_0_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__SOURCE), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getConcept(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_6_0_0_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_6_0_0_0_0_0_0, BENTO_7_0_0_6_0_0_0_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_6_0_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_6_0_0_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_6_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_6_0_0_0_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_6_0_0_1_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("target", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_7_0_0_6_0_0_1_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__TARGET), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getConcept(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_6_0_0_1_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_6_0_0_1_0_0_0, BENTO_7_0_0_6_0_0_1_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_6_0_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_6_0_0_1_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_6_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_6_0_0_1_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_6_0_0_2_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("source", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_7_0_0_6_0_0_2_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__SOURCE_MODELS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getParameterModel(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_6_0_0_2_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_6_0_0_2_0_0_0, BENTO_7_0_0_6_0_0_2_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_6_0_0_2_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_6_0_0_2_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_6_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_6_0_0_2_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_6_0_0_3_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("target", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_7_0_0_6_0_0_3_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__TARGET_MODELS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getParameterModel(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_6_0_0_3_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_6_0_0_3_0_0_0, BENTO_7_0_0_6_0_0_3_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_6_0_0_3_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_6_0_0_3_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_6_0_0_3 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_6_0_0_3_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_6_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_6_0_0_0, BENTO_7_0_0_6_0_0_1, BENTO_7_0_0_6_0_0_2, BENTO_7_0_0_6_0_0_3);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_6_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_6_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_6 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_6_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.PLUS);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_7_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("variants", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_7_0_0_7_0_0_1_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__FORMAL_PARAMETERS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.variants.VariantsPackage.eINSTANCE.getParameter(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_7_0_0_1_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_7_0_0_1_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_7_0_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_7_0_0_1_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_7_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_7_0_0_1_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.PLUS);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_7_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_7_0_0_0, BENTO_7_0_0_7_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_7_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_7_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_7 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_7_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.QUESTIONMARK);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_7_0_0_8 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__COMPOSITION), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getComposition(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_9_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("tags", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_7_0_0_9_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__TAGS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getTag(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_9_0_0_2_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(",", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_7_0_0_9_0_0_2_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.COMPOSITE_COMPONENT__TAGS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.core.CorePackage.eINSTANCE.getTag(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_9_0_0_2_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_9_0_0_2_0_0_0, BENTO_7_0_0_9_0_0_2_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_9_0_0_2_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_9_0_0_2_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_9_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_9_0_0_2_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.STAR);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0_9_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_9_0_0_0, BENTO_7_0_0_9_0_0_1, BENTO_7_0_0_9_0_0_2);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0_0_9_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_9_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_7_0_0_9 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_7_0_0_9_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.QUESTIONMARK);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_7_0_0_10 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("}", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_7_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0_0, BENTO_7_0_0_1, BENTO_7_0_0_2, BENTO_7_0_0_3, BENTO_7_0_0_4, BENTO_7_0_0_5, BENTO_7_0_0_6, BENTO_7_0_0_7, BENTO_7_0_0_8, BENTO_7_0_0_9, BENTO_7_0_0_10);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_7_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_7_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_7 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.core.CorePackage.eINSTANCE.getCompositeComponent(), BENTO_7_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_8_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("binding", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_8_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getBindingDeclaration().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.BINDING_DECLARATION__NAME), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_8_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("=", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_8_0_0_3 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.core.CorePackage.eINSTANCE.getBindingDeclaration().getEStructuralFeature(bento.language.bentocomp.core.CorePackage.BINDING_DECLARATION__FILE_NAME), "QUOTED_34_34", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_8_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_8_0_0_0, BENTO_8_0_0_1, BENTO_8_0_0_2, BENTO_8_0_0_3);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_8_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_8_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_8 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.core.CorePackage.eINSTANCE.getBindingDeclaration(), BENTO_8_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_9_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("compose", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_9_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getComposition().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.COMPOSITION__STEP), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getCompositionStep(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_9_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_9_0_0_0, BENTO_9_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_9_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_9_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_9 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getComposition(), BENTO_9_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_10_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("xor", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_10_0_0_1_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("when", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_10_0_0_1_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getXor().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.XOR__CONDITIONS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getXorCond(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_10_0_0_1_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_10_0_0_1_0_0_0, BENTO_10_0_0_1_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_10_0_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_10_0_0_1_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_10_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_10_0_0_1_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.PLUS);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_10_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_10_0_0_0, BENTO_10_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_10_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_10_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_10 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getXor(), BENTO_10_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_11_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getXorCond().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.XOR_COND__VALUE), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getBooleanValue(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_11_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("->", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_11_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getXorCond().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.XOR_COND__STEP), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getCompositionStep(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_11_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_11_0_0_0, BENTO_11_0_0_1, BENTO_11_0_0_2);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_11_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_11_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_11 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getXorCond(), BENTO_11_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_12_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("apply", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_12_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.APPLY__COMPONENT), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_12_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("(", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_12_0_0_3 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.APPLY__INPUT_MODELS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_12_0_0_4_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(",", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_12_0_0_4_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.APPLY__INPUT_MODELS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_12_0_0_4_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_12_0_0_4_0_0_0, BENTO_12_0_0_4_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_12_0_0_4_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_12_0_0_4_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_12_0_0_4 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_12_0_0_4_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.STAR);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_12_0_0_5 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(")", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_12_0_0_6 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("->", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_12_0_0_7 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("(", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_12_0_0_8 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.APPLY__OUTPUT_MODELS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.QUESTIONMARK, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_12_0_0_9_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(",", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_12_0_0_9_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.APPLY__OUTPUT_MODELS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_12_0_0_9_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_12_0_0_9_0_0_0, BENTO_12_0_0_9_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_12_0_0_9_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_12_0_0_9_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_12_0_0_9 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_12_0_0_9_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.STAR);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_12_0_0_10 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(")", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_12_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_12_0_0_0, BENTO_12_0_0_1, BENTO_12_0_0_2, BENTO_12_0_0_3, BENTO_12_0_0_4, BENTO_12_0_0_5, BENTO_12_0_0_6, BENTO_12_0_0_7, BENTO_12_0_0_8, BENTO_12_0_0_9, BENTO_12_0_0_10);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_12_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_12_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_12 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply(), BENTO_12_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_13_0_0_0_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.APPLY_PARAMETER__MODEL), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_13_0_0_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_13_0_0_0_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_13_0_0_0_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.APPLY_PARAMETER__BINDING), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_13_0_0_0_0_1_1 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("(", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_13_0_0_0_0_1_2 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.APPLY_PARAMETER__MODEL), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_13_0_0_0_0_1_3 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(")", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_13_0_0_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_13_0_0_0_0_1_0, BENTO_13_0_0_0_0_1_1, BENTO_13_0_0_0_0_1_2, BENTO_13_0_0_0_0_1_3);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_13_0_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_13_0_0_0_0_0, BENTO_13_0_0_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_13_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_13_0_0_0_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_13_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_13_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_13_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_13_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_13 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter(), BENTO_13_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_14_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("seq", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_14_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getSeq().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.SEQ__STEPS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getCompositionStep(), }, 1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_14_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getSeq().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.SEQ__STEPS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.PLUS, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getCompositionStep(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_14_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_14_0_0_0, BENTO_14_0_0_1, BENTO_14_0_0_2);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_14_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_14_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_14 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getSeq(), BENTO_14_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_15_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getFeatureRef().getEStructuralFeature(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.FEATURE_REF__FEATURE), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_15_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_15_0_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_15_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_15_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_15 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.flowcontrol.FlowcontrolPackage.eINSTANCE.getFeatureRef(), BENTO_15_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_16_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("atl", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_16_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getAtlTemplate().getEStructuralFeature(bento.language.bentocomp.technologies.TechnologiesPackage.ATL_TEMPLATE__TEMPLATE), "QUOTED_34_34", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_16_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("with", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_16_0_0_3 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getAtlTemplate().getEStructuralFeature(bento.language.bentocomp.technologies.TechnologiesPackage.ATL_TEMPLATE__PARAMETERS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_16_0_0_4_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(",", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoContainment BENTO_16_0_0_4_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoContainment(bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getAtlTemplate().getEStructuralFeature(bento.language.bentocomp.technologies.TechnologiesPackage.ATL_TEMPLATE__PARAMETERS), bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter(), }, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_16_0_0_4_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_16_0_0_4_0_0_0, BENTO_16_0_0_4_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_16_0_0_4_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_16_0_0_4_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_16_0_0_4 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_16_0_0_4_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.STAR);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_16_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_16_0_0_0, BENTO_16_0_0_1, BENTO_16_0_0_2, BENTO_16_0_0_3, BENTO_16_0_0_4);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_16_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_16_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_16 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getAtlTemplate(), BENTO_16_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_17_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter().getEStructuralFeature(bento.language.bentocomp.technologies.TechnologiesPackage.ATL_PARAMETER__ATL_MODEL_NAME), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_17_0_0_1_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword(":", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_17_0_0_1_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter().getEStructuralFeature(bento.language.bentocomp.technologies.TechnologiesPackage.ATL_PARAMETER__ATL_METAMODEL_NAME), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_17_0_0_1_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_17_0_0_1_0_0_0, BENTO_17_0_0_1_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_17_0_0_1_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_17_0_0_1_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoCompound BENTO_17_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoCompound(BENTO_17_0_0_1_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.QUESTIONMARK);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_17_0_0_2 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("=", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_17_0_0_3 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter().getEStructuralFeature(bento.language.bentocomp.technologies.TechnologiesPackage.ATL_PARAMETER__MODEL), "TEXT", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_17_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_17_0_0_0, BENTO_17_0_0_1, BENTO_17_0_0_2, BENTO_17_0_0_3);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_17_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_17_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_17 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter(), BENTO_17_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoKeyword BENTO_18_0_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoKeyword("java", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder BENTO_18_0_0_1 = new bento.language.bentocomp.resource.bento.grammar.BentoPlaceholder(bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getJavaTemplate().getEStructuralFeature(bento.language.bentocomp.technologies.TechnologiesPackage.JAVA_TEMPLATE__QUALIFIED_CLASSNAME), "QUOTED_34_34", bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, 0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoSequence BENTO_18_0_0 = new bento.language.bentocomp.resource.bento.grammar.BentoSequence(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_18_0_0_0, BENTO_18_0_0_1);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoChoice BENTO_18_0 = new bento.language.bentocomp.resource.bento.grammar.BentoChoice(bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE, BENTO_18_0_0);
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule BENTO_18 = new bento.language.bentocomp.resource.bento.grammar.BentoRule(bento.language.bentocomp.technologies.TechnologiesPackage.eINSTANCE.getJavaTemplate(), BENTO_18_0, bento.language.bentocomp.resource.bento.grammar.BentoCardinality.ONE);
	
	public static String getSyntaxElementID(bento.language.bentocomp.resource.bento.grammar.BentoSyntaxElement syntaxElement) {
		if (syntaxElement == null) {
			// null indicates EOF
			return "<EOF>";
		}
		for (java.lang.reflect.Field field : bento.language.bentocomp.resource.bento.grammar.BentoGrammarInformationProvider.class.getFields()) {
			Object fieldValue;
			try {
				fieldValue = field.get(null);
				if (fieldValue == syntaxElement) {
					String id = field.getName();
					return id;
				}
			} catch (Exception e) { }
		}
		return null;
	}
	
	public static bento.language.bentocomp.resource.bento.grammar.BentoSyntaxElement getSyntaxElementByID(String syntaxElementID) {
		try {
			return (bento.language.bentocomp.resource.bento.grammar.BentoSyntaxElement) bento.language.bentocomp.resource.bento.grammar.BentoGrammarInformationProvider.class.getField(syntaxElementID).get(null);
		} catch (Exception e) {
			return null;
		}
	}
	
	public final static bento.language.bentocomp.resource.bento.grammar.BentoRule[] RULES = new bento.language.bentocomp.resource.bento.grammar.BentoRule[] {
		BENTO_0,
		BENTO_1,
		BENTO_2,
		BENTO_3,
		BENTO_4,
		BENTO_5,
		BENTO_6,
		BENTO_7,
		BENTO_8,
		BENTO_9,
		BENTO_10,
		BENTO_11,
		BENTO_12,
		BENTO_13,
		BENTO_14,
		BENTO_15,
		BENTO_16,
		BENTO_17,
		BENTO_18,
	};
	
	/**
	 * Returns all keywords of the grammar. This includes all literals for boolean and
	 * enumeration terminals.
	 */
	public java.util.Set<String> getKeywords() {
		if (this.keywords == null) {
			this.keywords = new java.util.LinkedHashSet<String>();
			for (bento.language.bentocomp.resource.bento.grammar.BentoRule rule : RULES) {
				findKeywords(rule, this.keywords);
			}
		}
		return keywords;
	}
	
	/**
	 * Finds all keywords in the given element and its children and adds them to the
	 * set. This includes all literals for boolean and enumeration terminals.
	 */
	private void findKeywords(bento.language.bentocomp.resource.bento.grammar.BentoSyntaxElement element, java.util.Set<String> keywords) {
		if (element instanceof bento.language.bentocomp.resource.bento.grammar.BentoKeyword) {
			keywords.add(((bento.language.bentocomp.resource.bento.grammar.BentoKeyword) element).getValue());
		} else if (element instanceof bento.language.bentocomp.resource.bento.grammar.BentoBooleanTerminal) {
			keywords.add(((bento.language.bentocomp.resource.bento.grammar.BentoBooleanTerminal) element).getTrueLiteral());
			keywords.add(((bento.language.bentocomp.resource.bento.grammar.BentoBooleanTerminal) element).getFalseLiteral());
		} else if (element instanceof bento.language.bentocomp.resource.bento.grammar.BentoEnumerationTerminal) {
			bento.language.bentocomp.resource.bento.grammar.BentoEnumerationTerminal terminal = (bento.language.bentocomp.resource.bento.grammar.BentoEnumerationTerminal) element;
			for (String key : terminal.getLiteralMapping().keySet()) {
				keywords.add(key);
			}
		}
		for (bento.language.bentocomp.resource.bento.grammar.BentoSyntaxElement child : element.getChildren()) {
			findKeywords(child, this.keywords);
		}
	}
	
}
