<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mismatches"
    nsURI="http://genericity/mismatches" nsPrefix="mismatches">
  <eSubpackages name="core" nsURI="http://genericity/mismatches/core" nsPrefix="mismatches_core">
    <eClassifiers xsi:type="ecore:EClass" name="Model">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
          eType="#//core/MClass" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mismatches" upperBound="-1"
          eType="#//core/ClassMismatch" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
          eType="#//core/MFeature" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mismatch" lowerBound="1"
          eType="#//core/ClassMismatch" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="problems" upperBound="-1"
          eType="#//problem/Problem" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MFeature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MReference" eSuperTypes="#//core/MFeature"/>
    <eClassifiers xsi:type="ecore:EClass" name="MAttribute" eSuperTypes="#//core/MFeature"/>
    <eClassifiers xsi:type="ecore:EClass" name="Mismatch" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="problems" upperBound="-1"
          eType="#//problem/Problem" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="NameConflictConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassMismatch" abstract="true" eSuperTypes="#//core/Mismatch"/>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureMismatch" abstract="true" eSuperTypes="#//core/Mismatch"/>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeMismatch" abstract="true"
        eSuperTypes="#//core/FeatureMismatch"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceMismatch" abstract="true"
        eSuperTypes="#//core/FeatureMismatch"/>
    <eClassifiers xsi:type="ecore:EClass" name="Hint" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceToIntermediate" eSuperTypes="#//core/Hint"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassRenaming" eSuperTypes="#//core/ClassMismatch">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="conceptMetaclass" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="concreteMetaclass" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureRenaming" eSuperTypes="#//core/FeatureMismatch">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dConceptClass" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conceptClass" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="conceptFeature" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="concreteFeature" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="equalNames" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="featureBinding" eType="ecore:EClass ../../genericity_dsl/Metamodel/genericity_dsl.ecore#/0/BaseFeatureBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DoubleRole" eSuperTypes="#//core/ClassMismatch">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dConcreteClass" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dConceptClasses" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="concreteClass" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conceptClasses" upperBound="-1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="problem" nsURI="http://genericity/mismatches/problems" nsPrefix="mismatches_problems">
    <eClassifiers xsi:type="ecore:EClass" name="Problem" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Error" abstract="true" eSuperTypes="#//problem/Problem"/>
    <eClassifiers xsi:type="ecore:EClass" name="Warning" abstract="true" eSuperTypes="#//problem/Problem"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassNotFound" abstract="true" eSuperTypes="#//problem/Error">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WithInvolvedClasses" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dInvolvedConceptClasses"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="involvedConceptClasses"
          upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConceptClassNotFound" eSuperTypes="#//problem/ClassNotFound"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConcreteClassNotFound" eSuperTypes="#//problem/ClassNotFound"/>
    <eClassifiers xsi:type="ecore:EClass" name="NotMappedClass" eSuperTypes="#//problem/Error #//problem/WithInvolvedClasses"/>
    <eClassifiers xsi:type="ecore:EClass" name="NotMappedFeature" eSuperTypes="#//problem/Error #//problem/WithInvolvedClasses">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TooManyFeatureBindings" eSuperTypes="#//problem/Error #//problem/WithInvolvedClasses">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureNameClash" eSuperTypes="#//problem/Error #//problem/WithInvolvedClasses">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RuleConflict" eSuperTypes="#//problem/Warning #//problem/WithInvolvedClasses">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="info" nsURI="http://genericity/mismatches/info" nsPrefix="mismatches_info">
    <eClassifiers xsi:type="ecore:EClass" name="ConcreteClassNotMapped">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dInvolvedConcreteClass"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="involvedConcreteClass"
          lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
