<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="atl_analysis"
    nsURI="http://bento/analysis/atl/analysis" nsPrefix="atl_analysis">
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="problems" upperBound="-1"
        eType="#//Problem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisInfo" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Problem" abstract="true" eSuperTypes="#//AnalysisInfo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Recovery" abstract="true"/>
  <eSubpackages name="atl_error" nsURI="http://bento/analysis/atl/analysis/errors"
      nsPrefix="atl_error">
    <eClassifiers xsi:type="ecore:EClass" name="LocalProblem" abstract="true" eSuperTypes="#//Problem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="recovery" eType="#//Recovery"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NavigationProblem" abstract="true"
        eSuperTypes="#//atl_error/LocalProblem"/>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionOperationOverNoCollectionError"
        eSuperTypes="#//atl_error/NavigationProblem"/>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureNotFound" eSuperTypes="#//atl_error/NavigationProblem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="atl_recovery" nsURI="http://bento/analysis/atl/analysis/recovery"
      nsPrefix="atl_recovery">
    <eClassifiers xsi:type="ecore:EClass" name="FeatureFoundInSubclass" eSuperTypes="#//Recovery">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subclassName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
