/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package genericity.language.gcomponent.resource.gcomponent.grammar;

public class GcomponentGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public final static GcomponentGrammarInformationProvider INSTANCE = new GcomponentGrammarInformationProvider();
	
	private java.util.Set<String> keywords;
	
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_0_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.dsl.DslPackage.eINSTANCE.getDefinitionRoot().getEStructuralFeature(genericity.language.gcomponent.dsl.DslPackage.DEFINITION_ROOT__COMPONENT), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getComponent(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_0_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.dsl.DslPackage.eINSTANCE.getDefinitionRoot(), GCOMPONENT_0_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_1_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("transformation", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_1_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("component", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_1_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.TRANSFORMATION_COMPONENT__NAME), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_1_0_0_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("{", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_1_0_0_4_0_0_0_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("source", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_1_0_0_4_0_0_0_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.TRANSFORMATION_COMPONENT__SOURCE), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getConcept(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_1_0_0_4_0_0_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_4_0_0_0_0_0_0, GCOMPONENT_1_0_0_4_0_0_0_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_1_0_0_4_0_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_4_0_0_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_1_0_0_4_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_1_0_0_4_0_0_0_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_1_0_0_4_0_0_1_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("target", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_1_0_0_4_0_0_1_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.TRANSFORMATION_COMPONENT__TARGET), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getConcept(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_1_0_0_4_0_0_1_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_4_0_0_1_0_0_0, GCOMPONENT_1_0_0_4_0_0_1_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_1_0_0_4_0_0_1_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_4_0_0_1_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_1_0_0_4_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_1_0_0_4_0_0_1_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_1_0_0_4_0_0_2_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("source", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_1_0_0_4_0_0_2_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.TRANSFORMATION_COMPONENT__SOURCE_MODELS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getParameterModel(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_1_0_0_4_0_0_2_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_4_0_0_2_0_0_0, GCOMPONENT_1_0_0_4_0_0_2_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_1_0_0_4_0_0_2_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_4_0_0_2_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_1_0_0_4_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_1_0_0_4_0_0_2_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_1_0_0_4_0_0_3_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("target", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_1_0_0_4_0_0_3_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.TRANSFORMATION_COMPONENT__TARGET_MODELS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getParameterModel(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_1_0_0_4_0_0_3_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_4_0_0_3_0_0_0, GCOMPONENT_1_0_0_4_0_0_3_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_1_0_0_4_0_0_3_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_4_0_0_3_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_1_0_0_4_0_0_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_1_0_0_4_0_0_3_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_1_0_0_4_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_4_0_0_0, GCOMPONENT_1_0_0_4_0_0_1, GCOMPONENT_1_0_0_4_0_0_2, GCOMPONENT_1_0_0_4_0_0_3);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_1_0_0_4_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_4_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_1_0_0_4 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_1_0_0_4_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.PLUS);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_1_0_0_5_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("variants", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_1_0_0_5_0_0_1_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.TRANSFORMATION_COMPONENT__FORMAL_PARAMETERS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.variants.VariantsPackage.eINSTANCE.getParameter(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_1_0_0_5_0_0_1_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_5_0_0_1_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_1_0_0_5_0_0_1_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_5_0_0_1_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_1_0_0_5_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_1_0_0_5_0_0_1_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.PLUS);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_1_0_0_5_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_5_0_0_0, GCOMPONENT_1_0_0_5_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_1_0_0_5_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_5_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_1_0_0_5 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_1_0_0_5_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.QUESTIONMARK);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_1_0_0_6 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("definition", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_1_0_0_7 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTransformationComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.TRANSFORMATION_COMPONENT__TEMPLATE), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTemplate(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_1_0_0_8 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("}", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_1_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0_0, GCOMPONENT_1_0_0_1, GCOMPONENT_1_0_0_2, GCOMPONENT_1_0_0_3, GCOMPONENT_1_0_0_4, GCOMPONENT_1_0_0_5, GCOMPONENT_1_0_0_6, GCOMPONENT_1_0_0_7, GCOMPONENT_1_0_0_8);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_1_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_1_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTransformationComponent(), GCOMPONENT_1_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_2_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("concept", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_2_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getConcept().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.CONCEPT__NAME), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_2_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword(":", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_2_0_0_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getConcept().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.CONCEPT__URI), "QUOTED_34_34", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_2_0_0_4_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("tags", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_2_0_0_4_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword(":", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_2_0_0_4_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getConcept().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.CONCEPT__TAGS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.PLUS, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTag(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_2_0_0_4_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_2_0_0_4_0_0_0, GCOMPONENT_2_0_0_4_0_0_1, GCOMPONENT_2_0_0_4_0_0_2);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_2_0_0_4_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_2_0_0_4_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_2_0_0_4 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_2_0_0_4_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.QUESTIONMARK);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_2_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_2_0_0_0, GCOMPONENT_2_0_0_1, GCOMPONENT_2_0_0_2, GCOMPONENT_2_0_0_3, GCOMPONENT_2_0_0_4);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_2_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_2_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getConcept(), GCOMPONENT_2_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_3_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("model", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_3_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getParameterModel().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.PARAMETER_MODEL__NAME), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_3_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword(":", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_3_0_0_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getParameterModel().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.PARAMETER_MODEL__TYPE), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_3_0_0_4_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("=", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_3_0_0_4_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getParameterModel().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.PARAMETER_MODEL__RESOURCE_NAME), "QUOTED_34_34", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_3_0_0_4_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_3_0_0_4_0_0_0, GCOMPONENT_3_0_0_4_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_3_0_0_4_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_3_0_0_4_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_3_0_0_4 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_3_0_0_4_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.QUESTIONMARK);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_3_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_3_0_0_0, GCOMPONENT_3_0_0_1, GCOMPONENT_3_0_0_2, GCOMPONENT_3_0_0_3, GCOMPONENT_3_0_0_4);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_3_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_3_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getParameterModel(), GCOMPONENT_3_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_4_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTag().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.TAG__VALUE), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_4_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_4_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_4_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_4_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_4 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getTag(), GCOMPONENT_4_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_5_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("-", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_5_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.variants.VariantsPackage.eINSTANCE.getSingleFeature().getEStructuralFeature(genericity.language.gcomponent.variants.VariantsPackage.SINGLE_FEATURE__NAME), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_5_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_5_0_0_0, GCOMPONENT_5_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_5_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_5_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_5 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.variants.VariantsPackage.eINSTANCE.getSingleFeature(), GCOMPONENT_5_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_6_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("+", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_6_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.variants.VariantsPackage.eINSTANCE.getXorFeature().getEStructuralFeature(genericity.language.gcomponent.variants.VariantsPackage.XOR_FEATURE__NAME), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_6_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("xor", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_6_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_6_0_0_0, GCOMPONENT_6_0_0_1, GCOMPONENT_6_0_0_2);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_6_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_6_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_6 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.variants.VariantsPackage.eINSTANCE.getXorFeature(), GCOMPONENT_6_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_7_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("composite", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_7_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("component", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_7_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.COMPOSITE_COMPONENT__NAME), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_7_0_0_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("{", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_7_0_0_4_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("uses", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_7_0_0_4_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.COMPOSITE_COMPONENT__USES), "QUOTED_34_34", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_7_0_0_4_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_4_0_0_0, GCOMPONENT_7_0_0_4_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_7_0_0_4_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_4_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_7_0_0_4 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_7_0_0_4_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_7_0_0_5_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.COMPOSITE_COMPONENT__BINDINGS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getBindingDeclaration(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_7_0_0_5_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_5_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_7_0_0_5_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_5_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_7_0_0_5 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_7_0_0_5_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.QUESTIONMARK);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_7_0_0_6_0_0_0_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("source", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_7_0_0_6_0_0_0_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.COMPOSITE_COMPONENT__SOURCE), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getConcept(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_7_0_0_6_0_0_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_6_0_0_0_0_0_0, GCOMPONENT_7_0_0_6_0_0_0_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_7_0_0_6_0_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_6_0_0_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_7_0_0_6_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_7_0_0_6_0_0_0_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_7_0_0_6_0_0_1_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("target", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_7_0_0_6_0_0_1_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.COMPOSITE_COMPONENT__TARGET), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getConcept(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_7_0_0_6_0_0_1_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_6_0_0_1_0_0_0, GCOMPONENT_7_0_0_6_0_0_1_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_7_0_0_6_0_0_1_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_6_0_0_1_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_7_0_0_6_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_7_0_0_6_0_0_1_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_7_0_0_6_0_0_2_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("source", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_7_0_0_6_0_0_2_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.COMPOSITE_COMPONENT__SOURCE_MODELS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getParameterModel(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_7_0_0_6_0_0_2_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_6_0_0_2_0_0_0, GCOMPONENT_7_0_0_6_0_0_2_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_7_0_0_6_0_0_2_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_6_0_0_2_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_7_0_0_6_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_7_0_0_6_0_0_2_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_7_0_0_6_0_0_3_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("target", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_7_0_0_6_0_0_3_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.COMPOSITE_COMPONENT__TARGET_MODELS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.core.CorePackage.eINSTANCE.getParameterModel(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_7_0_0_6_0_0_3_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_6_0_0_3_0_0_0, GCOMPONENT_7_0_0_6_0_0_3_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_7_0_0_6_0_0_3_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_6_0_0_3_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_7_0_0_6_0_0_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_7_0_0_6_0_0_3_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_7_0_0_6_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_6_0_0_0, GCOMPONENT_7_0_0_6_0_0_1, GCOMPONENT_7_0_0_6_0_0_2, GCOMPONENT_7_0_0_6_0_0_3);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_7_0_0_6_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_6_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_7_0_0_6 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_7_0_0_6_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.PLUS);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_7_0_0_7_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("variants", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_7_0_0_7_0_0_1_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.COMPOSITE_COMPONENT__FORMAL_PARAMETERS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.variants.VariantsPackage.eINSTANCE.getParameter(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_7_0_0_7_0_0_1_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_7_0_0_1_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_7_0_0_7_0_0_1_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_7_0_0_1_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_7_0_0_7_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_7_0_0_7_0_0_1_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.PLUS);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_7_0_0_7_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_7_0_0_0, GCOMPONENT_7_0_0_7_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_7_0_0_7_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_7_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_7_0_0_7 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_7_0_0_7_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.QUESTIONMARK);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_7_0_0_8 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getCompositeComponent().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.COMPOSITE_COMPONENT__COMPOSITION), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getComposition(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_7_0_0_9 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("}", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_7_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0_0, GCOMPONENT_7_0_0_1, GCOMPONENT_7_0_0_2, GCOMPONENT_7_0_0_3, GCOMPONENT_7_0_0_4, GCOMPONENT_7_0_0_5, GCOMPONENT_7_0_0_6, GCOMPONENT_7_0_0_7, GCOMPONENT_7_0_0_8, GCOMPONENT_7_0_0_9);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_7_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_7_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_7 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getCompositeComponent(), GCOMPONENT_7_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_8_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("binding", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_8_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getBindingDeclaration().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.BINDING_DECLARATION__NAME), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_8_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("=", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_8_0_0_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getBindingDeclaration().getEStructuralFeature(genericity.language.gcomponent.core.CorePackage.BINDING_DECLARATION__FILE_NAME), "QUOTED_34_34", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_8_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_8_0_0_0, GCOMPONENT_8_0_0_1, GCOMPONENT_8_0_0_2, GCOMPONENT_8_0_0_3);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_8_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_8_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_8 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.core.CorePackage.eINSTANCE.getBindingDeclaration(), GCOMPONENT_8_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_9_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("compose", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_9_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getComposition().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.COMPOSITION__STEP), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getCompositionStep(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_9_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_9_0_0_0, GCOMPONENT_9_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_9_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_9_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_9 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getComposition(), GCOMPONENT_9_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_10_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("xor", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_10_0_0_1_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("when", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_10_0_0_1_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getXor().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.XOR__CONDITIONS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getXorCond(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_10_0_0_1_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_10_0_0_1_0_0_0, GCOMPONENT_10_0_0_1_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_10_0_0_1_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_10_0_0_1_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_10_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_10_0_0_1_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.PLUS);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_10_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_10_0_0_0, GCOMPONENT_10_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_10_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_10_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_10 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getXor(), GCOMPONENT_10_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_11_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getXorCond().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.XOR_COND__VALUE), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getBooleanValue(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_11_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("->", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_11_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getXorCond().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.XOR_COND__STEP), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getCompositionStep(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_11_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_11_0_0_0, GCOMPONENT_11_0_0_1, GCOMPONENT_11_0_0_2);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_11_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_11_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_11 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getXorCond(), GCOMPONENT_11_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_12_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("apply", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_12_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.APPLY__COMPONENT), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_12_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("(", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_12_0_0_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.APPLY__INPUT_MODELS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_12_0_0_4_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword(",", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_12_0_0_4_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.APPLY__INPUT_MODELS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_12_0_0_4_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_12_0_0_4_0_0_0, GCOMPONENT_12_0_0_4_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_12_0_0_4_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_12_0_0_4_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_12_0_0_4 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_12_0_0_4_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.STAR);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_12_0_0_5 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword(")", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_12_0_0_6 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("->", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_12_0_0_7 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("(", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_12_0_0_8 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.APPLY__OUTPUT_MODELS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.QUESTIONMARK, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_12_0_0_9_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword(",", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_12_0_0_9_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.APPLY__OUTPUT_MODELS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_12_0_0_9_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_12_0_0_9_0_0_0, GCOMPONENT_12_0_0_9_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_12_0_0_9_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_12_0_0_9_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_12_0_0_9 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_12_0_0_9_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.STAR);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_12_0_0_10 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword(")", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_12_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_12_0_0_0, GCOMPONENT_12_0_0_1, GCOMPONENT_12_0_0_2, GCOMPONENT_12_0_0_3, GCOMPONENT_12_0_0_4, GCOMPONENT_12_0_0_5, GCOMPONENT_12_0_0_6, GCOMPONENT_12_0_0_7, GCOMPONENT_12_0_0_8, GCOMPONENT_12_0_0_9, GCOMPONENT_12_0_0_10);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_12_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_12_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_12 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApply(), GCOMPONENT_12_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_13_0_0_0_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.APPLY_PARAMETER__MODEL), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_13_0_0_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_13_0_0_0_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_13_0_0_0_0_1_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.APPLY_PARAMETER__BINDING), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_13_0_0_0_0_1_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("(", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_13_0_0_0_0_1_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.APPLY_PARAMETER__MODEL), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_13_0_0_0_0_1_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword(")", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_13_0_0_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_13_0_0_0_0_1_0, GCOMPONENT_13_0_0_0_0_1_1, GCOMPONENT_13_0_0_0_0_1_2, GCOMPONENT_13_0_0_0_0_1_3);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_13_0_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_13_0_0_0_0_0, GCOMPONENT_13_0_0_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_13_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_13_0_0_0_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_13_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_13_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_13_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_13_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_13 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getApplyParameter(), GCOMPONENT_13_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_14_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("seq", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_14_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getSeq().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.SEQ__STEPS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getCompositionStep(), }, 1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_14_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getSeq().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.SEQ__STEPS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.PLUS, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getCompositionStep(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_14_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_14_0_0_0, GCOMPONENT_14_0_0_1, GCOMPONENT_14_0_0_2);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_14_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_14_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_14 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getSeq(), GCOMPONENT_14_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_15_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getFeatureRef().getEStructuralFeature(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.FEATURE_REF__FEATURE), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_15_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_15_0_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_15_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_15_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_15 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.flowcontrol.FlowcontrolPackage.eINSTANCE.getFeatureRef(), GCOMPONENT_15_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_16_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("atl", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_16_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getAtlTemplate().getEStructuralFeature(genericity.language.gcomponent.technologies.TechnologiesPackage.ATL_TEMPLATE__TEMPLATE), "QUOTED_34_34", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_16_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("with", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_16_0_0_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getAtlTemplate().getEStructuralFeature(genericity.language.gcomponent.technologies.TechnologiesPackage.ATL_TEMPLATE__PARAMETERS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_16_0_0_4_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword(",", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment GCOMPONENT_16_0_0_4_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentContainment(genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getAtlTemplate().getEStructuralFeature(genericity.language.gcomponent.technologies.TechnologiesPackage.ATL_TEMPLATE__PARAMETERS), genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter(), }, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_16_0_0_4_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_16_0_0_4_0_0_0, GCOMPONENT_16_0_0_4_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_16_0_0_4_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_16_0_0_4_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_16_0_0_4 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_16_0_0_4_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.STAR);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_16_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_16_0_0_0, GCOMPONENT_16_0_0_1, GCOMPONENT_16_0_0_2, GCOMPONENT_16_0_0_3, GCOMPONENT_16_0_0_4);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_16_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_16_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_16 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getAtlTemplate(), GCOMPONENT_16_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_17_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter().getEStructuralFeature(genericity.language.gcomponent.technologies.TechnologiesPackage.ATL_PARAMETER__ATL_MODEL_NAME), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_17_0_0_1_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword(":", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_17_0_0_1_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter().getEStructuralFeature(genericity.language.gcomponent.technologies.TechnologiesPackage.ATL_PARAMETER__ATL_METAMODEL_NAME), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_17_0_0_1_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_17_0_0_1_0_0_0, GCOMPONENT_17_0_0_1_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_17_0_0_1_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_17_0_0_1_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound GCOMPONENT_17_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCompound(GCOMPONENT_17_0_0_1_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.QUESTIONMARK);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_17_0_0_2 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("=", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_17_0_0_3 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter().getEStructuralFeature(genericity.language.gcomponent.technologies.TechnologiesPackage.ATL_PARAMETER__MODEL), "TEXT", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_17_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_17_0_0_0, GCOMPONENT_17_0_0_1, GCOMPONENT_17_0_0_2, GCOMPONENT_17_0_0_3);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_17_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_17_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_17 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getAtlParameter(), GCOMPONENT_17_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword GCOMPONENT_18_0_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword("java", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder GCOMPONENT_18_0_0_1 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentPlaceholder(genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getJavaTemplate().getEStructuralFeature(genericity.language.gcomponent.technologies.TechnologiesPackage.JAVA_TEMPLATE__QUALIFIED_CLASSNAME), "QUOTED_34_34", genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, 0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence GCOMPONENT_18_0_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSequence(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_18_0_0_0, GCOMPONENT_18_0_0_1);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice GCOMPONENT_18_0 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentChoice(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE, GCOMPONENT_18_0_0);
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule GCOMPONENT_18 = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule(genericity.language.gcomponent.technologies.TechnologiesPackage.eINSTANCE.getJavaTemplate(), GCOMPONENT_18_0, genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentCardinality.ONE);
	
	public static String getSyntaxElementID(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSyntaxElement syntaxElement) {
		if (syntaxElement == null) {
			// null indicates EOF
			return "<EOF>";
		}
		for (java.lang.reflect.Field field : genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentGrammarInformationProvider.class.getFields()) {
			Object fieldValue;
			try {
				fieldValue = field.get(null);
				if (fieldValue == syntaxElement) {
					String id = field.getName();
					return id;
				}
			} catch (Exception e) { }
		}
		return null;
	}
	
	public static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSyntaxElement getSyntaxElementByID(String syntaxElementID) {
		try {
			return (genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSyntaxElement) genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentGrammarInformationProvider.class.getField(syntaxElementID).get(null);
		} catch (Exception e) {
			return null;
		}
	}
	
	public final static genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule[] RULES = new genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule[] {
		GCOMPONENT_0,
		GCOMPONENT_1,
		GCOMPONENT_2,
		GCOMPONENT_3,
		GCOMPONENT_4,
		GCOMPONENT_5,
		GCOMPONENT_6,
		GCOMPONENT_7,
		GCOMPONENT_8,
		GCOMPONENT_9,
		GCOMPONENT_10,
		GCOMPONENT_11,
		GCOMPONENT_12,
		GCOMPONENT_13,
		GCOMPONENT_14,
		GCOMPONENT_15,
		GCOMPONENT_16,
		GCOMPONENT_17,
		GCOMPONENT_18,
	};
	
	/**
	 * Returns all keywords of the grammar. This includes all literals for boolean and
	 * enumeration terminals.
	 */
	public java.util.Set<String> getKeywords() {
		if (this.keywords == null) {
			this.keywords = new java.util.LinkedHashSet<String>();
			for (genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentRule rule : RULES) {
				findKeywords(rule, this.keywords);
			}
		}
		return keywords;
	}
	
	/**
	 * Finds all keywords in the given element and its children and adds them to the
	 * set. This includes all literals for boolean and enumeration terminals.
	 */
	private void findKeywords(genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSyntaxElement element, java.util.Set<String> keywords) {
		if (element instanceof genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword) {
			keywords.add(((genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentKeyword) element).getValue());
		} else if (element instanceof genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentBooleanTerminal) {
			keywords.add(((genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentBooleanTerminal) element).getTrueLiteral());
			keywords.add(((genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentBooleanTerminal) element).getFalseLiteral());
		} else if (element instanceof genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentEnumerationTerminal) {
			genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentEnumerationTerminal terminal = (genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentEnumerationTerminal) element;
			for (String key : terminal.getLiteralMapping().keySet()) {
				keywords.add(key);
			}
		}
		for (genericity.language.gcomponent.resource.gcomponent.grammar.GcomponentSyntaxElement child : element.getChildren()) {
			findKeywords(child, this.keywords);
		}
	}
	
}
