<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scenes_bdsl" nsURI="wakame.scene_bdsl" nsPrefix="wakame.scene_bdsl">
  <eClassifiers xsi:type="ecore:EClass" name="History">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenes" lowerBound="1"
        upperBound="-1" eType="#//Scene" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsMetamodelElement"
        upperBound="-1" eType="#//MetamodelElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsIntermediateElement"
        upperBound="-1" eType="#//IntemediateElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsFeatureClass" upperBound="-1"
        eType="#//FeatureClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsMetamodelElementFeature"
        upperBound="-1" eType="#//FeatureClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scene" eSuperTypes="#//NamedElement #//BindingElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Scene"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//Comment"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsnameScene" eType="#//nameScene"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Character" eSuperTypes="#//Element #//BindingElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsnameCharacter"
        eType="#//nameCharacter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//Element #//BindingElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsnamePlace" eType="#//namePlace"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//NamedElement #//BindingElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="characters" lowerBound="1"
        upperBound="-1" eType="#//Character"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ActionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsnameAction" eType="#//nameAction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containstypeAction" eType="#//typeAction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//BindingElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containstextComment" eType="#//textComment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionType">
    <eLiterals name="FIGHT"/>
    <eLiterals name="LOVE" value="1"/>
    <eLiterals name="DIE" value="2"/>
    <eLiterals name="CALL" value="3"/>
    <eLiterals name="MOVE" value="4"/>
    <eLiterals name="TALK" value="5"/>
    <eLiterals name="WRITE" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="nameScene" eSuperTypes="#//FeatureClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="nameCharacter" eSuperTypes="#//FeatureClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="namePlace" eSuperTypes="#//FeatureClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="nameAction" eSuperTypes="#//FeatureClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="typeAction" eSuperTypes="#//FeatureClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//ActionType"
        defaultValueLiteral="FIGHT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="textComment" eSuperTypes="#//FeatureClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BindingElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MetamodelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodelElementFeature"
        upperBound="-1" eType="#//MetamodelElementFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntemediateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingElement" lowerBound="1"
        eType="#//BindingElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodElelement" lowerBound="1"
        eType="#//MetamodelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetamodelElementFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureClass" upperBound="-1"
        eType="#//FeatureClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureClass" abstract="true"/>
</ecore:EPackage>
