/**
 *
 * $Id$
 */
package graph_bdsl.validation;

import graph_bdsl.Node;
import graph_bdsl.labelEdge;
import graph_bdsl.srcEdge21;
import graph_bdsl.tgtEdge22;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link graph_bdsl.Edge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EdgeValidator {
	boolean validate();

	boolean validateLabel(String value);
	boolean validateSrc(Node value);
	boolean validateTgt(Node value);
	boolean validateEref_srcEdge21(srcEdge21 value);
	boolean validateEref_tgtEdge22(tgtEdge22 value);
	boolean validateContainslabelEdge(EList<labelEdge> value);
}
