/**
 *
 * $Id$
 */
package graph_bdsl.validation;

import graph_bdsl.BindingAttribute;
import graph_bdsl.BindingElement;
import graph_bdsl.Edge;
import graph_bdsl.IntermediateElement;
import graph_bdsl.MetamodelElement;
import graph_bdsl.MetamodelElementFeature;
import graph_bdsl.Node;
import graph_bdsl.NoneElement;
import graph_bdsl.VirtualAttribute;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link graph_bdsl.GraphModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GraphModelValidator {
	boolean validate();

	boolean validateNode(EList<Node> value);
	boolean validateEdge(EList<Edge> value);
	boolean validateContainsNoneElement(EList<NoneElement> value);
	boolean validateContainsBindingElement(EList<BindingElement> value);
	boolean validateContainsIntermediateElement(EList<IntermediateElement> value);
	boolean validateContainsMetamodelElement(EList<MetamodelElement> value);
	boolean validateContainsMetamodelElementFeature(EList<MetamodelElementFeature> value);
	boolean validateContainsBindingAttribute(EList<BindingAttribute> value);
	boolean validateContainsVirtualAttribute(EList<VirtualAttribute> value);
	boolean validateSourceMM(String value);
}
