/**
 *
 * $Id$
 */
package graph_bdsl.validation;

import graph_bdsl.BindingElement;
import graph_bdsl.MetamodelElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link graph_bdsl.IntermediateElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IntermediateElementValidator {
	boolean validate();

	boolean validateBindingElement(BindingElement value);
	boolean validateMetamodelElement(EList<MetamodelElement> value);
	boolean validateId_target(String value);
}
