/**
 *
 * $Id$
 */
package graph_bdsl.validation;

import graph_bdsl.MetamodelElementFeature;
import graph_bdsl.VirtualAttribute;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link graph_bdsl.MetamodelElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MetamodelElementValidator {
	boolean validate();

	boolean validateVirtualAttribute(EList<VirtualAttribute> value);
	boolean validateMetamodelElementFeature(EList<MetamodelElementFeature> value);
	boolean validateName(String value);
}
