/**
 *
 * $Id$
 */
package graph_bdsl.validation;

import graph_bdsl.BindingAttribute;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link graph_bdsl.MetamodelElementFeature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MetamodelElementFeatureValidator {
	boolean validate();

	boolean validateFeatureClass(EList<BindingAttribute> value);
	boolean validateName(String value);
}
